import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './types/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* ---- Brand (product spec) ---- */
        brand: {
          forest: '#1E3B2B',
          ochre: '#F59E0B',
          offwhite: '#F9FAF6',
          success: '#22C55E',
          danger: '#EF4444',
        },
        /* ---- Material Design 3 tokens (from DESIGN.md) ---- */
        primary: '#072517',
        'on-primary': '#ffffff',
        'primary-container': '#1E3B2B',
        'on-primary-container': '#85A590',
        'inverse-primary': '#ADCEB8',
        'primary-fixed': '#C9EBD3',
        'primary-fixed-dim': '#ADCEB8',
        'on-primary-fixed': '#032112',
        'on-primary-fixed-variant': '#304D3C',

        secondary: '#855300',
        'on-secondary': '#ffffff',
        'secondary-container': '#FEA619',
        'on-secondary-container': '#684000',
        'secondary-fixed': '#FFDDB8',
        'secondary-fixed-dim': '#FFB95F',
        'on-secondary-fixed': '#2A1700',
        'on-secondary-fixed-variant': '#653E00',

        tertiary: '#00270C',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003F18',
        'on-tertiary-container': '#00B753',
        'tertiary-fixed': '#6BFF8F',
        'tertiary-fixed-dim': '#4AE176',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005321',

        error: '#BA1A1A',
        'on-error': '#ffffff',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',

        background: '#F1FCF2',
        'on-background': '#141E17',
        surface: '#F1FCF2',
        'on-surface': '#141E17',
        'on-surface-variant': '#424843',
        'surface-tint': '#476553',
        'surface-dim': '#D2DDD3',
        'surface-bright': '#F1FCF2',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#EBF7EC',
        'surface-container': '#E6F1E6',
        'surface-container-high': '#E0EBE1',
        'surface-container-highest': '#DAE5DB',

        'inverse-surface': '#29332C',
        'inverse-on-surface': '#E8F4E9',
        outline: '#727973',
        'outline-variant': '#C2C8C1',

        /* ---- Semantic price states ---- */
        'price-up': '#15803D',
        'price-up-bg': '#DCFCE7',
        'price-down': '#B91C1C',
        'price-down-bg': '#FEE2E2',
        'price-stable': '#B45309',
        'price-stable-bg': '#FEF3C7',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
        '2xl': '2rem',
      },
      spacing: {
        gutter: '1rem',
        margin: '1rem',
        'margin-tablet': '1.5rem',
        'margin-desktop': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
      },
      fontFamily: {
        sans: [
          'var(--font-outfit)',
          'var(--font-tiro-hi)',
          'var(--font-tiro-mr)',
          'var(--font-noto-bengali)',
          'var(--font-noto-tamil)',
          'var(--font-noto-telugu)',
          'var(--font-noto-kannada)',
          'var(--font-noto-gujarati)',
          'var(--font-noto-odia)',
          'sans-serif',
        ],
        body: [
          'var(--font-outfit)',
          'var(--font-tiro-hi)',
          'var(--font-tiro-mr)',
          'var(--font-noto-bengali)',
          'var(--font-noto-tamil)',
          'var(--font-noto-telugu)',
          'var(--font-noto-kannada)',
          'var(--font-noto-gujarati)',
          'var(--font-noto-odia)',
          'sans-serif',
        ],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'price-hero': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'price-hero-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-lg': ['16px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
      boxShadow: {
        card: '0 1px 6px rgba(16, 32, 24, 0.05)',
        lift: '0 6px 16px rgba(28, 38, 31, 0.12)',
        'focus-ochre': '0 0 0 3px rgba(245, 158, 11, 0.25)',
      },
      keyframes: {
        'mic-pulse': {
          '0%': { transform: 'scale(1)', opacity: '0.6' },
          '100%': { transform: 'scale(1.9)', opacity: '0' },
        },
        'bar-wave': {
          '0%, 100%': { transform: 'scaleY(0.35)' },
          '50%': { transform: 'scaleY(1)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'mic-pulse': 'mic-pulse 1.6s ease-out infinite',
        'bar-wave': 'bar-wave 1s ease-in-out infinite',
        'fade-up': 'fade-up 0.35s ease-out both',
      },
    },
  },
  plugins: [],
};

export default config;